[package]
name = "clip-bridge"
version = "0.1.9"
edition = "2024"
authors = ["苏向夜 <fu050409@163.com>"]
description = "Sync your X11 and Wayland clipboard seamlessly"
license = "MIT"
repository = "https://github.com/noctisynth/clip-bridge"
readme = "README.md"
keywords = ["clipboard", "sync", "wayland", "x11"]
categories = ["command-line-utilities"]

[package.metadata.aur]
depends = [
  "wayland",
  "wayland-protocols",
  "libx11",
  "libxkbcommon",
  "libxkbcommon-x11"
]
optdepends = ["wl-clipboard", "xclip"]

[dependencies]
# Utils
nix = { version = "0.31.1", features = ["fs", "poll"] }
thiserror = "2.0.20"
tokio = { version = "1.35", default-features = false, features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# Wayland Related
wayland-client = "0.31"
wayland-protocols = { version = "0.32.10", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.3.10", features = ["client"] }
x11rb = { version = "0.13", default-features = false, features = ["xfixes"] }

[dev-dependencies]
wayland-protocols-wlr = { version = "0.3.10", features = ["server"] }
wayland-server = "0.31"
